Work today got me exhausted... I’m so stressed...
I miss the old days.. When all my worries were things like, “I wonder what's momma’s cooking for dinner” or “I need to kill this level’s boss”
That's right! Maybe if I play a little on my old GameBoy I can relax a bit!
