...
Ouch… My head hurts…
I still can’t move… 
What's this.. Am I bleeding?
So.. Am I trapped in this game for real?!
And Everytime that monster touches me… it's getting worse
I need to get out of here…
I must keep going and collect the three other coins…